# Generated by Django 3.1.2 on 2021-02-14 06:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201212_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contet',
            field=ckeditor.fields.RichTextField(verbose_name='Contenido'),
        ),
    ]
